#!/bin/bash
#
# Build the Harmony DRLVM VM from svn head
#
# Revision: $Id:$
# Date:     $Date:$
#

#
# Command line parameters
#
TOP=$1
[ -z "$TOP" ] && {
  echo "Usage: $0 scratch-dir"
  exit 1
}
shift

while [ ! -z "$1" ]; do
  case $1 in 
    clean) rm -rf $TOP/harmony
           ;;
    *) 	   echo "Unrecognized parameter \"$1\""
       	   exit 1
       	   ;;
  esac
  shift
done

#
# Internal parameters
#
BIN=$HOME/dacapo_regressions
VMTOP=$TOP/harmony/working_vm/
#export JAVA_HOME=/opt/ibm-java2-i386-50
export JAVA_HOME=/opt/jdk1.5.0_07
export PATH=$JAVA_HOME/bin:$PATH

ECJ_DIR=$TOP/harmony/working_classlib/depends/jars/ecj_3.2/
ANT_URL=http://www.apache.org/dist/ant/
HARMONY_SVN=https://svn.apache.org/repos/asf/harmony/enhanced/trunk

build_ant() {
  if [ ! -e $TOP/apache-ant-1.6.5 ]; then (
    "Downloading ant"
    cd $TOP
    wget -c $ANT_URL/ant-current-bin.zip
    unzip ant-current-bin.zip
  )
  fi
}

build_classlib() {
  (
    echo "Building class library"
    cd working_classlib
    ant fetch-depends
    
    ant -lib $ECJ_DIR
  )
}

build_vm() {
  (
    echo "Building the VM"
    BUILD=$VMTOP/build
    cd $BUILD
    cp $BIN/drlvm.properties $BUILD/drlvm.properties

    #
    # Force the right gcc version.  eurgh.
    #
    #mkdir $VMTOP/bin_tmp
    #ln -s /usr/bin/gcc-3.3 $VMTOP/bin_tmp/gcc
    #ln -s /usr/bin/gcc++-3.3 $VMTOP/bin_tmp/g++

    echo "Updating dependencies"
    chmod +x build.sh
    $BUILD/build.sh update && {

      echo "Building"
      #export PATH=$VMTOP/bin_tmp:$PATH
      $BUILD/build.sh
    }
  )
}

(
svn co $HARMONY_SVN $TOP/harmony
cd $TOP/harmony

echo "Populating source"
ant populate_source

build_ant
export ANT_HOME=$TOP/apache-ant-1.6.5

build_classlib
build_vm
)
