#!/bin/bash
#
# config.
#
# Configuration variables for DaCapo benchmarks.  "source"d into
# the main shell scripts to pick up symbols.
#

export BIN=$HOME/dacapo_regressions
export SCRATCH=$HOME/tmp
export JAVA_HOME_14=/usr/lib/j2se/1.4
#export JAVA_HOME_15=/opt/jdk1.5.0
export JAVA_HOME_15=/opt/ibm-java2-i386-50

export ALL_VMS="DRLVM JIKESRVM SUN JDK16 J9 JROCKIT"
export ALL_BMS="antlr bloat chart eclipse fop hsqldb jython luindex lusearch pmd sunflow xalan"
export ALL_SIZES="small default large"
export PUBLIC_HOST=war.anu.edu.au
export PUBLIC_PATH=/cs/pub/people/Robin.Garner/dacapo/regression/
export PUBLIC=$PUBLIC_HOST:$PUBLIC_PATH
export PERF_VMS="JIKESRVM DRLVM SUN JDK16 J9 JROCKIT"

