#!/bin/bash
#
# Nightly regressions for dacapo
#

HERE=$(dirname $0)

if [ -z "$1" ]; then
  . $HERE/config
else
  . $1
fi

DSTAMP=$(date +%Y%m%d)
TOP=$SCRATCH/dacapo-nightly-$DSTAMP
DACAPO_SVNHOME=https://svn.sourceforge.net/svnroot/dacapobench
DACAPO_BRANCH=benchmarks/trunk
#DACAPO_BRANCH=benchmarks/branches/robin
RVM_SVNHOME=https://svn.sourceforge.net/svnroot/jikesrvm
ANT=/usr/bin/ant

#
# Pick up system-specific parameters
#
SYSCONFIG=$BIN/$(uname -m).nightly.config
if [ -e $SYSCONFIG ]; then
  . $SYSCONFIG
fi

#
# JikesRVM configuration variabes
#
RVM_CONFIG=FastAdaptiveGenMS
export RVM_ROOT=$TOP/rvm_trunk

#
# Create the working directory and other initialization tasks
#
init() {
  if [ -e $TOP ]
  then
    rm -rf $TOP
  fi
  mkdir $TOP
  mkdir $TOP/results-$DSTAMP
}

#
# Build the dacapo benchmarks from SVN head
#
build_dacapo() {
  ( 
    set -x
    export JAVA_HOME=$JAVA_HOME_15

    cd $TOP

    svn co $DACAPO_SVNHOME/$DACAPO_BRANCH dacapo

    cd dacapo/benchmarks
    if [ -d $BIN/sources ]; then
      cp -r $BIN/sources .
      BUILD_PARAMS=dist
    else
      BUILD_PARAMS="sources dist"
    fi
    $ANT $BUILD_PARAMS
    cp dacapo-$DSTAMP.jar $TOP 

    # Archive the build
    cp dacapo-$DSTAMP.jar $BIN/builds/
  )
}

(
  init
  build_dacapo
  if [ ! -e $TOP/dacapo-$DSTAMP.jar ]; then
    echo "ERROR: dacapo benchmarks failed to build."
    exit 1
  fi

  if $(echo $ALL_VMS | grep JIKESRVM > /dev/null); then
    $BIN/build_jikesrvm $TOP $RVM_CONFIG &> $TOP/results-$DSTAMP/jikesrvm.build.log
    export RVM_BUILD=$RVM_ROOT/builds/$RVM_CONFIG
    if [ ! -e $RVM_BUILD/JikesRVM ]; then
      echo "ERROR: JikesRVM failed to build."
    fi
  fi

  if $(echo $ALL_VMS | grep DRLVM > /dev/null); then
    $BIN/build_harmony $TOP/harmony &> $TOP/results-$DSTAMP/drlvm.build.log
    export DRLVM_HOME=$TOP/harmony/harmony/working_vm/build/lnx_ia32_gcc_release/deploy/jdk
    if [ ! -e $DRLVM_HOME/jre/bin/java ]; then
      echo "ERROR: DRLVM failed to build."
    fi
  fi

  if [ "$1" = "test" ]; then
    exit
  fi

  ( cd $TOP; 
    $BIN/test_dacapo $DSTAMP # "JIKESRVM DRLVM"
  ) && { 
      rm -rf $TOP
  }
) > $HOME/nightly.$DSTAMP.log 2>&1
