#!/bin/bash

if [ -z "$1" ]; then
  echo "Insufficient arguments"
  exit 1
fi

tmpfile=/tmp/trim.$USER.$$
for file in $*; do
  if [ ! -e $file ]; then
    echo "$file does not exist"
  else
    head -n 10000 $file >$tmpfile
    mv $tmpfile $file
  fi
done
